# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "192.168.33.30"
  config.vm.provision :shell, path: "provision/bootstrap.sh"

  config.vm.synced_folder "../sources/", "/home/warehouse",
    create: true,
    owner: "www-data",
    group: "www-data",
    mount_options: ["dmode=770,fmode=660"]

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
end
